version: '3'

services:
  redis1:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6379:6379'
    volumes:
      - 'redis1_data:/bitnami/redis/data'

  redis2:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6380:6379'
    volumes:
      - 'redis2_data:/bitnami/redis/data'

  redis3:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6381:6379'
    volumes:
      - 'redis3_data:/bitnami/redis/data'

  redis4:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6382:6379'
    volumes:
      - 'redis4_data:/bitnami/redis/data'

  redis5:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6383:6379'
    volumes:
      - 'redis5_data:/bitnami/redis/data'

  redis6:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6384:6379'
    volumes:
      - 'redis6_data:/bitnami/redis/data'

  redis7:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6385:6379'
    volumes:
      - 'redis7_data:/bitnami/redis/data'

  redis8:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6386:6379'
    volumes:
      - 'redis8_data:/bitnami/redis/data'

  grpc_server:
    build: ./grpc_server
    container_name: grpc_server
    ports:
      - "50051:50051"
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - redis7
      - redis8

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - grpc_server
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - redis7
      - redis8

volumes:
  redis1_data:
    driver: local
  redis2_data:
    driver: local
  redis3_data:
    driver: local
  redis4_data:
    driver: local
  redis5_data:
    driver: local
  redis6_data:
    driver: local
  redis7_data:
    driver: local
  redis8_data:
    driver: local

