version: '3'

services:
  redis1:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6379:6379'
    volumes:
      - 'redis1_data:/bitnami/redis/data'

  redis2:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6380:6379'
    volumes:
      - 'redis2_data:/bitnami/redis/data'

  redis3:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6381:6379'
    volumes:
      - 'redis3_data:/bitnami/redis/data'

  redis4:
    image: docker.io/bitnami/redis:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru 
    ports:
      - '6382:6379'
    volumes:
      - 'redis4_data:/bitnami/redis/data'

  grpc_server:
    build: ./grpc_server  # Asume que tienes un Dockerfile para el servidor gRPC
    container_name: grpc_server
    ports:
      - "50051:50051"
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4

  api:
    build: ./api  # Asume que tienes un Dockerfile para la API
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - grpc_server
      - redis1
      - redis2
      - redis3
      - redis4

volumes:
  redis1_data:
    driver: local
  redis2_data:
    driver: local
  redis3_data:
    driver: local
  redis4_data:
    driver: local
