# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x05\x63\x61\x63he\" \n\x0eResolveRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"*\n\x0cResolveReply\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t2D\n\x0b\x44NSResolver\x12\x35\n\x07Resolve\x12\x15.cache.ResolveRequest\x1a\x13.cache.ResolveReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOLVEREQUEST']._serialized_start=22
  _globals['_RESOLVEREQUEST']._serialized_end=54
  _globals['_RESOLVEREPLY']._serialized_start=56
  _globals['_RESOLVEREPLY']._serialized_end=98
  _globals['_DNSRESOLVER']._serialized_start=100
  _globals['_DNSRESOLVER']._serialized_end=168
# @@protoc_insertion_point(module_scope)
